export const cocktails = [
  ////////////////////////////////
  /////   LIGHT COCKTAILS    /////
  ////////////////////////////////
  {
    id: 1,
    title: 'APEROL SPRITZ',
    category: 'light',
    price: 40,
    desc: `Modern prosecco classic with aromas of orange, gentian, chichona bark. And don’t forget the eye-catching color.`,
  },
  {
    id: 2,
    title: 'HUGO',
    category: 'light',
    price: 40,
    desc: `Another modern classic made with prosecco, fresh limes, fresh mint leaves and aromatic elderflower syrup. Delicious and sweet.`,
  },
  {
    id: 3,
    title: 'FRENCH 75',
    category: 'light',
    price: 50,
    desc: `Gin and champagne make a bubbly wonderful duo which is why this cocktail is always a good idea.`,
  },
  {
    id: 4,
    title: 'LA VIE EN ROSE',
    category: 'light',
    price: 48,
    desc: `Rose bud essences combined with italian aperitivo and french dry vermouth. It’s light, sparkling, feminine easy-sipper.`,
  },
  {
    id: 5,
    title: "PIMM'S CUP",
    category: 'light',
    price: 50,
    desc: `Quintessential english summer cocktail, we make it old fashioned way: with citrus, cucumbers, mint and spicy ginger beer.`,
  },
  {
    id: 6,
    title: 'ROSSO AND TONIC',
    category: 'light',
    price: 58,
    desc: `Bitter-sweet and harmonious, highly perfumed and herbal character of vermouth enhanced with tonic water.`,
  },
  {
    id: 7,
    title: 'SLOE GIN FIZZ',
    category: 'light',
    price: 63,
    desc: `Sloe gin combined with elderflower syrup and fresh lemon juice is a perfect combo for hot summer days.`,
  },
  {
    id: 8,
    title: 'MIDORI SOUR',
    category: 'light',
    price: 48,
    desc: `With this cult japanese watermelon liqueur mixed with fresh citrus juice and soda we get closest to disco drinks – funky & quite sweet. 80’s reloaded.`,
  },
  {
    id: 9,
    title: 'BREEZE',
    category: 'light',
    price: 45,
    desc: `A classic wine spritz cocktail upgraded with elderflower liqueur and fresh lemon juice.`,
  },

  ////////////////////////////////
  /////  CLASSIC COCKTAILS   /////
  ////////////////////////////////

  {
    id: 10,
    title: 'EARL GREY NORTHSIDE',
    category: 'classic',
    price: 65,
    desc: `Aquavit based with home-made earl grey tea syrup, peated malt spray, hibiscus & pepper dust and some exotic bitters. Exotic!!!`,
  },
  {
    id: 11,
    title: 'OLD FASHIONED',
    category: 'classic',
    price: 68,
    desc: `Arguably  world’s oldest cocktail – and one of the best. We make it bourbon based, oranges and aromatic bitters. Big & sexy classic for self-confident and those who seek self-confidence.`,
  },
  {
    id: 12,
    title: "TOMMY'S MARGARITA",
    category: 'classic',
    price: 68,
    desc: `One of the most popular margarita variations. Substituting cointreau for agave syrup. Crisp and agave-forward taste.`,
  },
  {
    id: 13,
    title: 'HEMINGWAY DAQUIRI',
    category: 'classic',
    price: 63,
    desc: `The combo of light rum, lime, grapefruit juice and maraschino liqueur make for a bracing, complex cocktail that - unlike daquiris that suffer from excess sweetnes - finishes nice and dry.`,
  },
  {
    id: 14,
    title: 'WHITE LADY',
    category: 'classic',
    price: 68,
    desc: `Frothy and elegant classic from the golden age of cocktails, powered by gin, french orange liqueur an fresh lemon juice.`,
  },
  {
    id: 15,
    title: 'ANTIQUE',
    category: 'classic',
    price: 45,
    desc: `Based on popular local liqueur ”pelinkovac” combined with almond syrup, orange and fresh lime juice. Perfect for hot summer nights.`,
  },
  {
    id: 16,
    title: 'CHARLIE CHAPLIN',
    category: 'classic',
    price: 63,
    desc: `This cocktail is definetely perfect when you have a sweet tooth. It’s made with gin, apricot brandy and lime juice.`,
  },
  {
    id: 17,
    title: 'THE GODFATHER',
    category: 'classic',
    price: 53,
    desc: `A favourite since the ‘70s , the godfather is a simple mixed drink of a scotch and amaretto. “We are gonna make you an offer you can’t refuse”`,
  },
  {
    id: 18,
    title: 'EL DON',
    category: 'classic',
    price: 78,
    desc: `Majestic cocktail: finest reposado tequila, coffee and orange liqueurs & aromatic and cirtus bitters. High class drink for serious drinkers and superb tequila afficionados.`,
  },
  {
    id: 19,
    title: 'GRASSHOPPER',
    category: 'classic',
    price: 58,
    desc: `Think of mint chocolate thin - get it? This is simple, creamy
    & sweet treat with some grated dark chocolate... Yummy`,
  },
  {
    id: 20,
    title: 'WHITE RUSSIAN',
    category: 'classic',
    price: 58,
    desc: `Simple & tasty - vodka & coffee liquor based creamy pleasure.`,
  },
  {
    id: 21,
    title: 'MOJITO, CAIPIRINHA or MOSCOW MULE',
    category: 'classic',
    price: 58,
    desc: `Popular summer cirtusy classics which will never get out of style. “If life gives you lemons, return them and ask for lime.”`,
  },
  {
    id: 22,
    title: 'AVIATION',
    category: 'classic',
    price: 63,
    desc: `Fabulous looking, mighty & complex classic, with gin, violet liqueur and maraschino. Fly to the moon – play among the stars.`,
  },
  {
    id: 23,
    title: 'MARTINI',
    category: 'classic',
    price: 63,
    desc: `“King of cocktails” – we like it gin & dry, but you can have it sweet, dirty, martinez, hanky panky or vodka - just like 007 agent. Beware of this one: elegance & complexity – with a licence to kill.`,
  },
  {
    id: 24,
    title: 'BASIL SMASH',
    category: 'classic',
    price: 63,
    desc: `“Špina bar classic – aromatic & refreshing sour powered by gin, fresh basil leaves and lemons. Taste of real mediterranean.`,
  },
  {
    id: 25,
    title: 'NEGRONI',
    category: 'classic',
    price: 63,
    desc: `Love it or hate it, this classic surely made a huuuuuge come-back lately. Harmonious blend of finest vermouth, bitter and gin. There is also chocholate negroni version.`,
  },
  {
    id: 26,
    title: 'ESPRESSO MARTINI',
    category: 'classic',
    price: 63,
    desc: `Funky espresso for booze lovers - made with style and smile
    (and freshly brewed espresso and plenty of gluten-free vodka). Mood uplifter!!`,
  },
  {
    id: 27,
    title: 'SOURS: WHISKY, PISCO or AMARETTO',
    category: 'classic',
    price: 65,
    desc: `You prefer powerful yet refreshing drink or you’re total sweet-tooth and you seek for sweet sensations – choose one of theese powerful frothy pleasures.`,
  },
];
