export const cocktails = [
  ////////////////////////////////
  /////   LIGHT COCKTAILS    /////
  ////////////////////////////////
  {
    id: 1,
    title: 'APEROL SPRITZ',
    category: 'light',
    price: 8.9,
    desc: `Modern prosecco classic with aromas of orange, gentian, chichona bark. And don’t forget the eye-catching color.`,
  },
  {
    id: 2,
    title: 'HUGO',
    category: 'light',
    price: 8.9,
    desc: `Another modern classic made with prosecco, fresh limes, fresh mint leaves and aromatic elderflower syrup. Delicious and sweet.`,
  },
  {
    id: 3,
    title: 'LA VIE EN ROSE',
    category: 'light',
    price: 9,
    desc: `Rose bud essences combined with Italian aperitivo, and french dry vermouth. It’s light, sparkling, feminine easy-sipper.`,
  },
  {
    id: 4,
    title: 'MARTINI FIERO/TONIC',
    category: 'light',
    price: 9,
    desc: `Martini fiero and tonic were made for each other – this contemporary vermouth is a blend of citrus and bittersweet orange – a perfect aperitif when mixed with tonic.`,
  },
  {
    id: 5,
    title: 'EPULON SPRITZ',
    category: 'light',
    price: 9.1,
    desc: `Sip on our epulon. Pelinkovac and amaro cocktail-a zesty fusion of lime juice, pink grapefruit soda and bold flavours.`,
  },
  {
    id: 6,
    title: 'TERANINO SPRITZ',
    category: 'light',
    price: 9.1,
    desc: `Enjoy our teranino cocktail-a lively blend of teranino, lime juice and soda for a refreshing burst of flavour.`,
  },
  {
    id: 7,
    title: 'BUBBLE BURST',
    category: 'light',
    price: 8.7,
    desc: `A refreshing delight in every sip- harmonius blend of traubi wine, lemon juice and white peach syrup.`,
  },
  {
    id: 8,
    title: 'SLOE GIN FIZZ',
    category: 'light',
    price: 10.5,
    desc: `A light and refreshing cocktail, consisting of sloe gin, elderflower syrup, lemon juice and sparking water.`,
  },
  {
    id: 9,
    title: 'MIDORI SOUR',
    category: 'light',
    price: 10,
    desc: `This cocktail bursting with Japanese melon flavour will satisfy your taste buds for something fruity, refreshing and sweet and sour.`,
  },

  ////////////////////////////////
  /////  CLASSIC COCKTAILS   /////
  ////////////////////////////////

  {
    id: 10,
    title: 'CHARLIE CHAPLIN',
    category: 'classic',
    price: 11.1,
    desc: `Light and refreshing. Especially good for hot summer nights when you’re looking for something nice and easy.`,
  },
  {
    id: 11,
    title: 'EARL GREY NORTHSIDE',
    category: 'classic',
    price: 11.4,
    desc: `Aquavit based with home-made earl grey tea syrup, peated malt spray, hibiscus & pepper dust and some exotic bitters. Exotic!!!`,
  },
  {
    id: 12,
    title: 'ALMOND OLD FASHIONED',
    category: 'classic',
    price: 11.3,
    desc: `Bourbons sweet notes are lifted and amplified by amaretto almond flavours.`,
  },
  {
    id: 13,
    title: 'HOTEL NATIONAL',
    category: 'classic',
    price: 11.1,
    desc: `A fruity but sophisticated riff on the classic daiquiri with pineapple juice and apricot liqueur.`,
  },

  {
    id: 14,
    title: 'PAPER PLANE',
    category: 'classic',
    price: 11.5,
    desc: `A delightfully complex, boozy modern cocktail with bourbon, aperol, amaro and freshly squeezed lemon juice.`,
  },
  {
    id: 15,
    title: 'SIDECAR',
    category: 'classic',
    price: 11.9,
    desc: `A classic sour cocktail that is made with cognac, orange liqueur and orange juice.`,
  },
  {
    id: 16,
    title: 'THE BLACK MANHATTAN',
    category: 'classic',
    price: 11.9,
    desc: `A classic manhattan with amaro in place of sweet vermouth. Heavier in style and with distinctive bitter chocholate and light spice.`,
  },
  {
    id: 17,
    title: 'MARTINI',
    category: 'classic',
    price: 11.3,
    desc: `“King of cocktails” – we like it gin & dry, but you can have it sweet, dirty, martinez, hanky panky or vodka - just like 007 agent. Beware of this one: elegance & complexity – with a licence to kill.`,
  },
  {
    id: 18,
    title: 'LITTLE MISS SUNSHINE',
    category: 'classic',
    price: 11.4,
    desc: `Experience our signature blend: Vodka’s embrace, Gingers zest, lemon’s kiss, and pineapple’s sway—an enchanting elixir, crafted to delight.`,
  },
  {
    id: 19,
    title: 'MOJITO, CAIPIRINHA or MOSCOW MULE',
    category: 'classic',
    price: 11,
    desc: `Popular summer cirtusy classics. Check out for season inspired versions of those cocktails with seasonal fruit pureés`,
  },
  {
    id: 20,
    title: 'BASIL SMASH',
    category: 'classic',
    price: 11.2,
    desc: `“Špina bar classic – aromatic & refreshing sour powered by gin, fresh basil leaves and lemons. Taste of real mediterranean.`,
  },
  {
    id: 21,
    title: 'MARGARITA',
    category: 'classic',
    price: 11.3,
    desc: `With 100% blue agave Tequila finest french orange liqueur and fresh lime juice.`,
  },
  {
    id: 22,
    title: 'NEGRONI',
    category: 'classic',
    price: 11.3,
    desc: `Love it or hate it, this classic surely made a huuuuuge come-back lately. Harmonious blend of finest vermouth, bitter and gin. There is also <strong>chocholate negroni version</strong>.`,
  },
  {
    id: 23,
    title: 'ESPRESSO MARTINI',
    category: 'classic',
    price: 11.3,
    desc: `Funky espresso for booze lovers - made with style and smile
    (and freshly brewed espresso and plenty of gluten-free vodka). Mood uplifter!!`,
  },
  {
    id: 24,
    title: 'SOURS: WHISKY, PISCO or AMARETTO',
    category: 'classic',
    price: 11.3,
    desc: `You prefer powerful yet refreshing drink or you’re total sweet-tooth and you seek for sweet sensations – choose one of theese powerful frothy pleasures.`,
  },
  {
    id: 25,
    title: 'PALOMA',
    category: 'classic',
    price: 11.5,
    desc: `The iconic mexican drink balances sweet, sour and salty notes. Packs a boozy punch.`,
  },
  {
    id: 26,
    title: 'MANGO SMASH',
    category: 'classic',
    price: 11.2,
    desc: `Gin, mango and some lemon make for a frothy, sweet and sour, refreshing drink with mango as the main star.`,
  },
  {
    id: 27,
    title: 'MAN O’ WAR',
    category: 'classic',
    price: 11.3,
    desc: `A shaken whiskey cocktail that captures the complexity of a manhattan and packages it with bright lemon and orange.`,
  },
];
