export const cocktails = [
  ////////////////////////////////
  /////   LIGHT COCKTAILS    /////
  ////////////////////////////////
  {
    id: 1,
    title: 'APEROL SPRITZ',
    category: 'light',
    price: 45,
    desc: `Modern prosecco classic with aromas of orange, gentian, chichona bark. And don’t forget the eye-catching color.`,
  },
  {
    id: 2,
    title: 'HUGO',
    category: 'light',
    price: 45,
    desc: `Another modern classic made with prosecco, fresh limes, fresh mint leaves and aromatic elderflower syrup. Delicious and sweet.`,
  },
  {
    id: 3,
    title: 'ROSSO/BIANCO TONIC',
    category: 'light',
    price: 62,
    desc: `Bitter-sweet and harmonious, highly perfumed and herbal character of vermouth enhanced with tonic water.`,
  },
  {
    id: 4,
    title: 'LA VIE EN ROSE',
    category: 'light',
    price: 52,
    desc: `Rose bud essences combined with italian aperitivo and french dry vermouth. It’s light, sparkling, feminine easy-sipper.`,
  },
  {
    id: 5,
    title: 'PALOMA',
    category: 'light',
    price: 69,
    desc: `Paloma is spanish for ‘dove’. Reminiscent of a long fruity margarita with refreshing effervesence.`,
  },
  {
    id: 6,
    title: 'CHARLIE CHAPLIN',
    category: 'light',
    price: 67,
    desc: `This cocktail is definetely perfect when you have a sweet tooth. It’s made with gin, apricot brandy and lime juice.`,
  },
  {
    id: 7,
    title: 'JAPANESE SLIPPER',
    category: 'light',
    price: 67,
    desc: `Midori liqueur paired with cointreau for a hint of orange and the sweetnes of those 2 is offset with fresh squeezed lemon juice.`,
  },
  {
    id: 8,
    title: 'MIDORI SOUR',
    category: 'light',
    price: 52,
    desc: `With this cult japanese watermelon liqueur mixed with fresh citrus juice and soda we get closest to disco drinks – funky & quite sweet. 80’s reloaded.`,
  },
  {
    id: 9,
    title: 'SLOE GIN FIZZ',
    category: 'light',
    price: 67,
    desc: `Sloe gin combined with elderflower syrup and fresh lemon juice is a perfect combo for hot summer days.`,
  },

  ////////////////////////////////
  /////  CLASSIC COCKTAILS   /////
  ////////////////////////////////

  {
    id: 10,
    title: 'EARL GREY NORTHSIDE',
    category: 'classic',
    price: 69,
    desc: `Aquavit based with home-made earl grey tea syrup, peated malt spray, hibiscus & pepper dust and some exotic bitters. Exotic!!!`,
  },
  {
    id: 11,
    title: 'OLD FASHIONED',
    category: 'classic',
    price: 72,
    desc: `Arguably  world’s oldest cocktail – and one of the best. We make it bourbon based, oranges and aromatic bitters. Big & sexy classic for self-confident and those who seek self-confidence.`,
  },
  {
    id: 12,
    title: 'MARGARITA',
    category: 'classic',
    price: 72,
    desc: `With 100% blue agave tequila, finest french orange liqueur and fresh lime juice.  Get ready for fiesta Acapulco or Tijuana style.`,
  },
  {
    id: 13,
    title: 'HORSE’S NECK',
    category: 'classic',
    price: 72,
    desc: `This two-ingredient cocktail is an easy-to-make crowd pleaser, especially for those who like bourbon and ginger beer with bitters.`,
  },
  {
    id: 14,
    title: 'EAU DA VIE',
    category: 'classic',
    price: 62,
    desc: `Our signature cocktail made with quince brandy, elderflower syrup and lemon juice. Simple and refreshing.`,
  },
  {
    id: 15,
    title: 'ŽUŽU LILI',
    category: 'classic',
    price: 79,
    desc: `As fattennning as it is alcoholic, this indulgent, creamy dessert in a glass cocktail is served with generous innuendo.`,
  },
  {
    id: 16,
    title: 'INDUSTRY SOUR',
    category: 'classic',
    price: 67,
    desc: `The industry sour cocktail recipe gets it’s potency from the herbaceous green chartreuse and notes of menthol from fernet branca. It surprisingly works.`,
  },
  {
    id: 17,
    title: 'HEMINGWAY DAQUIRI',
    category: 'classic',
    price: 67,
    desc: `The combo of light rum, lime, grapefruit juice and maraschino liqueur make for a bracing, complex cocktail that-unlike daquiris that suffer from excess sweetnes-finishes nice and dry.`,
  },
  {
    id: 18,
    title: 'EL DON',
    category: 'classic',
    price: 82,
    desc: `Majestic cocktail: finest reposado tequila, coffee and orange liqueurs & aromatic and cirtus bitters. High class drink for serious drinkers and superb tequila afficionados.`,
  },
  {
    id: 19,
    title: 'GRASSHOPPER',
    category: 'classic',
    price: 62,
    desc: `Think of mint chocolate thin - get it? This is simple, creamy
    & sweet treat with some grated dark chocolate... Yummy`,
  },
  {
    id: 20,
    title: 'WHITE RUSSIAN',
    category: 'classic',
    price: 62,
    desc: `Simple & tasty - vodka & coffee liquor based creamy pleasure.`,
  },
  {
    id: 21,
    title: 'MOJITO, CAIPIRINHA or MOSCOW MULE',
    category: 'classic',
    price: 62,
    desc: `Popular summer cirtusy classics which will never get out of style. “If life gives you lemons, return them and ask for lime.”`,
  },
  {
    id: 22,
    title: 'AVIATION',
    category: 'classic',
    price: 67,
    desc: `Fabulous looking, mighty & complex classic, with gin, violet liqueur and maraschino. Fly to the moon – play among the stars.`,
  },
  {
    id: 23,
    title: 'MARTINI',
    category: 'classic',
    price: 67,
    desc: `“King of cocktails” – we like it gin & dry, but you can have it sweet, dirty, martinez, hanky panky or vodka - just like 007 agent. Beware of this one: elegance & complexity – with a licence to kill.`,
  },
  {
    id: 24,
    title: 'BASIL SMASH',
    category: 'classic',
    price: 67,
    desc: `“Špina bar classic – aromatic & refreshing sour powered by gin, fresh basil leaves and lemons. Taste of real mediterranean.`,
  },
  {
    id: 25,
    title: 'NEGRONI',
    category: 'classic',
    price: 67,
    desc: `Love it or hate it, this classic surely made a huuuuuge come-back lately. Harmonious blend of finest vermouth, bitter and gin. There is also <strong>chocholate negroni version</strong>.`,
  },
  {
    id: 26,
    title: 'ESPRESSO MARTINI',
    category: 'classic',
    price: 67,
    desc: `Funky espresso for booze lovers - made with style and smile
    (and freshly brewed espresso and plenty of gluten-free vodka). Mood uplifter!!`,
  },
  {
    id: 27,
    title: 'SOURS: WHISKY, PISCO or AMARETTO',
    category: 'classic',
    price: 70,
    desc: `You prefer powerful yet refreshing drink or you’re total sweet-tooth and you seek for sweet sensations – choose one of theese powerful frothy pleasures.`,
  },
];
