export const otherDrinks = [
  {
    id: 1,
    title: 'Pilsner Urquell, CZECHIA',
    category: 'beer',
    price: 19,
    desc: `Signature flavour balances sweetness from the triple-decocted malt, and bitterness from Saaz hops.
    The thick head of dense wet foam adds smoothness
    and seals in flavour and aroma.`,
  },
  {
    id: 2,
    title: 'Pale Ale, CROATIA',
    category: 'beer',
    price: 25,
    desc: `A beer of rich taste, fruity aroma and amber color was made with a specially selected combination of malts and American varieties of hops.`,
  },
  {
    id: 3,
    title: 'Siesta Session, CROATIA',
    category: 'beer',
    price: 25,
    desc: `A summer special without which we could not survive a year. Siesta is richly hopped IPA, very light and very drinkable, with fine tropical aromas that invite you to get more.`,
  },
  {
    id: 4,
    title: 'Neon Stout, CROATIA',
    category: 'beer',
    price: 27,
    desc: `A dark beer which will win you over with the exceptional fullness of flavor obtained by combining several special malts and cereals. You will not remain indifferent to the full taste accentuated by notes of black coffee and chocolate.`,
  },
  {
    id: 5,
    title: 'Madagascan Cola',
    category: 'softDrinks',
    price: 23,
    desc: `Expect citrus notes from the Mexican Tahitian limes, with a warm and gently spiced finish from the kola nut and the vanilla.`,
  },
  {
    id: 6,
    title: 'Indian Tonic',
    category: 'softDrinks',
    price: 23,
    desc: `Uses a handful of different botanicals, including our distinctive quinine and oils from Mexican Bitter Oranges, to give a uniquely clean and refreshing taste and aroma. `,
  },
  {
    id: 7,
    title: 'Bitter Lemon Tonic',
    category: 'softDrinks',
    price: 23,
    desc: `The sharpness of the Sicilian lemons and the gentle bitterness of the quinine brilliantly counterbalance the sweetness of sweet and fruity gins and really help bring out the fruit flavours that can otherwise be overpowered and lost.`,
  },
  {
    id: 8,
    title: 'Elderflower Tonic',
    category: 'softDrinks',
    price: 23,
    desc: `The delicate and sweet flavor of elderflower is perfectly balanced by the soft bitterness of the quinine, which pairs perfectly with fresh and floral gins and premium vodkas.`,
  },
  {
    id: 9,
    title: 'Ginger Ale',
    category: 'softDrinks',
    price: 23,
    desc: `A distinctive ginger flavour created by blending the world’s finest gingers. Added complexity comes from supportive citrus notes, resulting in an overwhelmingly clean finish – making this the perfect mixer for dark spirits.`,
  },
  {
    id: 10,
    title: 'Rose Lemonade',
    category: 'softDrinks',
    price: 23,
    desc: `Light and fruity, you’ll taste mostly sweet rose water and rose oils that mix with the citrus. This packs a tart citrus bang on the arrival that gets toned down once the rose oil notes blend with the lemon. Slightly sweet and fairly acidic.`,
  },
  {
    id: 11,
    title: 'Lemonade 0,30L',
    category: 'freshJuices',
    price: 19,
    desc: `Freshly squeezed, unpasteurized juice.`,
  },
  {
    id: 12,
    title: 'Orange Juice 0,20L',
    category: 'freshJuices',
    price: 25,
    desc: `Freshly squeezed, unpasteurized juice.`,
  },
  {
    id: 13,
    title: 'Jana Still Water',
    category: 'water',
    price: '12 / 27',
    desc: `On its thousand-year journey from the underground through layers of mineral rocks, Jana became naturally rich with minerals, which gives her a unique and recognizable silky taste.`,
  },
  {
    id: 14,
    title: 'Jamnica Sparkling Water',
    category: 'water',
    price: '12 / 27',
    desc: `Refreshing sparkling natural mineral water without any calories. It has a unique taste, balanced mineral composition and refreshing sparkling quality.`,
  },
];
