export const wines = [
  ////////////////////////////////
  /////      WHITE WINES     /////
  ////////////////////////////////
  {
    id: 1,
    title: 'ŠKRLET',
    winemaker: 'Voštinić-Klasnić',
    category: 'white',
    price: '3/20',
    year: '2023',
    location: `Moslavina`,
    desc: `Refreshing and light. Floral and fruity. Excellent aperitive dry wine.`,
  },
  {
    id: 2,
    title: 'MALVAZIJA',
    winemaker: 'Deklić',
    category: 'white',
    price: '4/28',
    year: '2023',
    location: `Istria`,
    desc: `Light bodied, dry but very complex aromas of citrus, fresh fruits and bitter almonds.`,
  },
  {
    id: 3,
    title: 'ZLATARICA',
    winemaker: 'Gašpar',
    category: 'white',
    price: '4/28',
    year: '2022',
    location: `Dalmatia`,
    desc: `Fresh and vibrant eith notes of red apples, quince, almonds and mediteraen herbs.`,
  },
  {
    id: 4,
    title: 'SAUVIGNON',
    winemaker: 'Štampar',
    category: 'white',
    price: '4.2/33',
    year: '2022',
    location: `Međimurje`,
    desc: `Aromatic and refreshing, green fruits and berries with citrusy and grassy aromas.`,
  },
  {
    id: 5,
    title: 'CHARDONNAY SINGLE PS',
    winemaker: 'Štampar',
    category: 'white',
    price: '4.5/35',
    year: '',
    location: `Međimurje`,
    desc: `A rich and full wine with a spicy character and well preserved freshness.`,
  },
  {
    id: 6,
    title: 'VENJE BIJELO',
    winemaker: 'Enjigi',
    category: 'white',
    price: '-/40',
    year: '2010',
    location: `Slavonia`,
    desc: `Full bodied and very complex aromatic cuvee of 5 varieties aged in oak for 18 months.`,
  },
  {
    id: 7,
    title: 'POŠIP NERICA',
    winemaker: 'Krajančić',
    category: 'white',
    price: '-/42',
    year: '2022',
    location: `Dalmatia`,
    desc: `Medium bodied, aromas of lemon, yellow fruit, ripe apples and mediterranean herbs.`,
  },
  {
    id: 8,
    title: 'VUGAVA',
    winemaker: 'Stina',
    category: 'white',
    price: '-/45',
    year: '2021',
    location: `Istria`,
    desc: `Rich aromas of apricots, ripe apples and citrus fruits with a hint of vanilla.`,
  },
  ////////////////////////////////
  /////      RED WINES       /////
  ////////////////////////////////
  {
    id: 9,
    title: 'CABERNET SAUVIGNON',
    winemaker: 'Ritoša',
    category: 'red',
    price: '4/26',
    year: '2017',
    location: `Istria`,
    desc: `Typical young CS aged in wood, wild red fruit, cassia and subtle hint of herbs and spices.`,
  },
  {
    id: 10,
    title: 'MERLOT SINGLE PS',
    winemaker: '',
    category: 'red',
    price: '4.5/30',
    year: '2021',
    location: `Dalmatia`,
    desc: `Smooth, well rounded, low acidity and medium-bodied wine.`,
  },
  {
    id: 11,
    title: 'PLAVAC MALI',
    winemaker: 'Miloš',
    category: 'red',
    price: '5/35',
    year: '2018',
    location: `Dalmatia`,
    desc: `Dry & medium body, loaded with black fruits, sweet spices, aromatic herbs & hint of oak.`,
  },
  {
    id: 12,
    title: 'R6 CUVEE',
    winemaker: 'Bibich',
    category: 'red',
    price: '5.8/37',
    year: '2019',
    location: `Dalmatia`,
    desc: `Medium-bodied and elegant wine, made of three indigenous grape varieties: babić, plavina and lasina. Rich in dark and red fruit, herbaceous and subtle touch of oak.`,
  },
  {
    id: 13,
    title: 'CICONIA NIGRA CUVEE',
    winemaker: 'Josić',
    category: 'red',
    price: '-/38',
    year: '2017',
    location: `Slavonia`,
    desc: `A beautiful cuvee with intense dark fruit aromas emanating from the bottle.`,
  },
  {
    id: 14,
    title: 'OTTOCENTO CRNI',
    winemaker: 'Clai',
    category: 'red',
    price: '-/51',
    year: '2016',
    location: `Istria`,
    desc: `Full-bodied organic cuveé full of ripe red and dark fruit, figs, wood floor & leaves.`,
  },
  {
    id: 15,
    title: 'GRAN TERAN',
    winemaker: 'Coronica',
    category: 'red',
    price: '-/51',
    year: '2018',
    location: `Istria`,
    desc: `Rich, spicy and rustic, a great wine full of dark fruits, jammy, meaty, leathery notes.`,
  },
  {
    id: 16,
    title: 'STAGNUM',
    winemaker: 'Miloš',
    category: 'red',
    price: '190/250/500',
    year: '2009/2005/2003',
    location: `Dalmatia`,
    desc: `Price is listed as per years below. Full bodied, deep and extremely complex, wine for meditation from cult croatian winemaker, aromas of dark & black fruits, carobs, figs and dates, aromatic herbs and christmas spice-box, 2003 and 2005 represent cult vintages.`,
  },
  ////////////////////////////////
  /////   SPARKLING WINES    /////
  ////////////////////////////////
  {
    id: 17,
    title: 'PROSECCO',
    winemaker: 'Ca’ DiI Alte',
    category: 'sparkling',
    price: '4.5/30',
    location: `Veneto, Italy`,
    desc: 'This Prosecco is a light straw yellow with fine bubbles. A pleasant bouquet with notes of pear and white flowers that follow onto a palate which is bright and clean with a refreshing finish.',
  },
  {
    id: 18,
    title: 'PET NAT',
    winemaker: 'Ščurek',
    category: 'sparkling',
    price: '-/32',
    location: `Slovenia`,
    desc: `Notes of red grape, peach, red apples and watermellon with a hint of orange flower.`,
  },
  {
    id: 19,
    title: 'PJENUŠAC',
    winemaker: 'Volarević',
    category: 'sparkling',
    price: '-/37',
    location: `South Croatia`,
    desc: `Easy sipping wine with notes of citrus, peach and apricots.`,
  },
  {
    id: 20,
    title: 'CHAMP. GRANDE SENDREÉ',
    winemaker: 'Drappier',
    category: 'sparkling',
    price: '-/130',
    year: '2006',
    location: `Champagne, France`,
    desc: `Full bodied and full developed vintage champagne, with great complexity and rich aromas of dry leaves, ripe fruits, butter cakes, lees, nuts and mineral notes.`,
  },
  ////////////////////////////////
  ///// ROSE & SWEET  WINES  /////
  ////////////////////////////////
  {
    id: 21,
    title: 'ROSELLA ROSE',
    winemaker: 'Poletti',
    category: 'rose',
    price: '4.5/28',
    year: '2022',
    location: `Istria`,
    desc: `Dry with notes of raspberries, strawberries and roses.`,
  },
  {
    id: 22,
    title: 'MUŠKAT',
    winemaker: 'Štampar',
    category: 'rose',
    price: '4.5/28',
    year: '2022',
    location: `Međimurje`,
    desc: `Very elegant, perfumed and not too sweet, notes of green grapes, fruits and flowers.`,
  },
  {
    id: 23,
    title: 'PROŠEK',
    winemaker: 'Matela',
    category: 'rose',
    price: '5/48',
    year: '',
    location: `Međimurje`,
    desc: `Very elegant, perfumed and not too sweet, notes of green grapes, fruits and flowers.`,
  },
];
