export const wines = [
  ////////////////////////////////
  /////      WHITE WINES     /////
  ////////////////////////////////
  {
    id: 1,
    title: 'ŠKRLET',
    winemaker: 'Voštinić-Klasnić',
    category: 'white',
    price: '19/135',
    year: '2019',
    location: `Moslavina`,
    desc: `Refreshing and light. Floral and fruity. Excellent aperitive dry wine.`,
  },
  {
    id: 2,
    title: 'CHARDONNAY ROSENBERG',
    winemaker: 'Krauthaker',
    category: 'white',
    price: '-/220',
    year: '2019',
    location: `Slavonia`,
    desc: `Fresh and complex wine. Fruity and aged in oak barrels. Notes of citrus, vanilla.`,
  },
  {
    id: 3,
    title: 'SAUVIGNON',
    winemaker: 'Štampar',
    category: 'white',
    price: '24/165',
    year: '2021',
    location: `Međimurje`,
    desc: `Aromatic and refreshing, green fruits and berries with citrusy and grassy aromas.`,
  },
  {
    id: 4,
    title: 'MALVAZIJA',
    winemaker: 'Deklić',
    category: 'white',
    price: '24/165',
    year: '2021',
    location: `Istria`,
    desc: `Light bodied, dry but very complex aromas of citrus, fresh fruits and bitter almonds.`,
  },
  {
    id: 5,
    title: 'VENJE BIJELO',
    winemaker: 'Enjingi',
    category: 'white',
    price: '-/240',
    year: '2010',
    location: `Slavonia`,
    desc: `Full bodied and very complex aromatic cuvee of 5 varieties aged in oak for 18 months.`,
  },
  {
    id: 6,
    title: 'POŠIP NERICA',
    winemaker: 'Krajančić',
    category: 'white',
    price: '-/230',
    year: '2021',
    location: `Dalmatia`,
    desc: `Medium bodied, aromas of lemon, yellow fruit, ripe apples and mediterranean herbs.`,
  },
  {
    id: 7,
    title: 'VUGAVA',
    winemaker: 'Stina',
    category: 'white',
    price: '-/250',
    year: '2021',
    location: `ISTRIA`,
    desc: `Rich aromas of apricots, ripe apples and citrus fruits with a hint of vanilla.`,
  },
  ////////////////////////////////
  /////      RED WINES       /////
  ////////////////////////////////
  {
    id: 10,
    title: 'PLAVAC MALI, bio*',
    winemaker: 'Miloš',
    category: 'red',
    price: '24/165',
    year: '2018',
    location: `Dalmatia`,
    desc: `Dry & medium body, loaded with black fruits, sweet spices, aromatic herbs & hint of oak.`,
  },
  {
    id: 11,
    title: 'CABERNET SAUVIGNON',
    winemaker: 'Ritoša',
    category: 'red',
    price: '25/170',
    year: '2016',
    location: `Istria`,
    desc: `Typical young CS aged in wood, wild red fruit, cassia and subtle hint of herbs and spices.`,
  },
  {
    id: 12,
    title: 'FRANKOVKA',
    winemaker: 'Kosovec',
    category: 'red',
    price: '26/180',
    year: '2017',
    location: `Moslavina`,
    desc: `Lively freshness combined with minerality, tobacco and dark fruit. Food-friendly wine.`,
  },
  {
    id: 13,
    title: 'R6 CUVEE',
    winemaker: 'Bibich',
    category: 'red',
    price: '35/240',
    year: '2019',
    location: `Dalmatia`,
    desc: `Medium-bodied and elegant wine, made of three indigenous grape varieties: babić, plavina and lasina. Rich in dark and red fruit, herbaceous and subtle touch of oak.`,
  },
  {
    id: 14,
    title: 'CICONIA NIGRA CUVEE',
    winemaker: 'Josić',
    category: 'red',
    price: '-/230',
    year: '2017',
    location: `Slavonia`,
    desc: `A beautiful cuvee with intense dark fruit aromas emanating from the bottle.`,
  },
  {
    id: 15,
    title: 'OTTOCENTO CRNI, bio*',
    winemaker: 'Clai',
    category: 'red',
    price: '-/325',
    year: '2015',
    location: `Istria`,
    desc: `Full-bodied organic cuveé full of ripe red and dark fruit, figs, wood floor & leaves.`,
  },
  {
    id: 16,
    title: 'GRAN TERAN',
    winemaker: 'Coronica',
    category: 'red',
    price: '-/335',
    year: '2015',
    location: `Istria`,
    desc: `Rich, spicy and rustic, a great wine full of dark fruits, jammy, meaty, leathery notes.`,
  },
  {
    id: 17,
    title: 'STAGNUM, bio*',
    winemaker: 'Miloš',
    category: 'red',
    price: '770/880/990',
    year: '2009/2005/2003',
    location: `Dalmatia`,
    desc: `Price is listed as per years below. Full bodied, deep and extremely complex, wine for meditation from cult croatian winemaker, aromas of dark & black fruits, carobs, figs and dates, aromatic herbs and christmas spice-box, 2003 and 2005 represent cult vintages.`,
  },
  ////////////////////////////////
  /////   SPARKLING WINES    /////
  ////////////////////////////////
  {
    id: 18,
    title: 'PROSECCO',
    winemaker: 'Ca’ DiI Alte',
    category: 'sparkling',
    price: '30/165',
    location: `Veneto, Italy`,
    desc: 'This Prosecco is a light straw yellow with fine bubbles. A pleasant bouquet with notes of pear and white flowers that follow onto a palate which is bright and clean with a refreshing finish.',
  },
  {
    id: 19,
    title: 'CHAMP. NV ROSE BRUT',
    winemaker: 'Drappier',
    category: 'sparkling',
    price: '-/790',
    location: `Champagne, France`,
    desc: `Wonderful dry rose champagne from the most famous boutique champagnerie.`,
  },
  {
    id: 20,
    title: 'CHAMP. GRANDE SENDREÉ',
    winemaker: 'Drappier',
    category: 'sparkling',
    price: '-/990',
    year: '2006',
    location: `Champagne, France`,
    desc: `Full bodied and full developed vintage champagne, with great complexity and rich aromas of dry leaves, ripe fruits, butter cakes, lees, nuts and mineral notes.`,
  },
  ////////////////////////////////
  ///// ROSE & SWEET  WINES  /////
  ////////////////////////////////
  {
    id: 21,
    title: 'ROSELLA ROSE',
    winemaker: 'Poletti',
    category: 'rose',
    price: '26/180',
    year: '2021',
    location: `Istria`,
    desc: `Dry, complex and fruity with notes of grenadine, rosebud, pink grapefruit & red berries.`,
  },
  {
    id: 22,
    title: 'MUŠKAT',
    winemaker: 'Štampar',
    category: 'rose',
    price: '26/180',
    year: '2021',
    location: `Međimurje`,
    desc: `Sweet type of wine. Very elegant, perfumed, notes of green grapes, fruits and flowers.`,
  },
  {
    id: 23,
    title: 'PORTO TAWNY PORT',
    winemaker: 'Fonseca',
    category: 'rose',
    price: '25/-',
    year: '-',
    location: `Portugal`,
    desc: `A medium tannin wine with notes of ripe, musky berries like raspberries and blackberries, bitter chocholate and buttery, nutty caramel.`,
  },
];
