export const wines = [
  ////////////////////////////////
  /////      WHITE WINES     /////
  ////////////////////////////////
  {
    id: 1,
    title: 'ŠKRLET Trdenić',
    category: 'white',
    price: '19/135',
    year: '2020',
    location: `POPOVAČA / MOSLAVINA, CENTRAL CROATIA`,
    desc: `Refreshing and light. Floral and fruity. Perfect aperitive dry wine.`,
  },
  {
    id: 2,
    title: 'PINOT GRIGIO Jagunić',
    category: 'white',
    price: '22/150',
    year: '2018',
    location: `PLEŠIVICA / CROATIAN UPLANDS, CROATIA`,
    desc: `Macerated and softened in an old oak for a short time, it’s fruity, citrusy and mineral.`,
  },
  {
    id: 3,
    title: 'SAUVIGNON Štampar',
    category: 'white',
    price: '24/165',
    year: '2019',
    location: `ŠTRIGOVA / MEĐIMURJE , NORTHERN CROATIA`,
    desc: `Aromatic and refreshing, green fruits and berries with citrusy and grassy aromas.`,
  },
  {
    id: 4,
    title: 'MALVAZIJA Deklić',
    category: 'white',
    price: '24/165',
    year: '2020',
    location: `VIŽINADA / WESTERN ISTRIA, CROATIA`,
    desc: `Refreshing istrian indigenous wine with floral, citrusy and herbal aromas.`,
  },
  {
    id: 5,
    title: 'VENJE Enjigi, organic',
    category: 'white',
    price: '30/205',
    year: '2010',
    location: `KUTJEVO / CENTRAL SLAVONIA, CROATIA`,
    desc: `Full bodied and very complex aromatic cuvee of 5 varieties aged in oak for 18 months.`,
  },
  {
    id: 6,
    title: 'POŠIP INTRADA Krajančić',
    category: 'white',
    price: '-/225',
    year: '2018',
    location: `ČARA / KORČULA ISLAND, SOUTHERN DALMATIA, CROATIA`,
    desc: `Medium bodied, aromas of lemon, yellow fruit, ripe apples and mediterranean herbs.`,
  },
  {
    id: 7,
    title: 'GRIMALDA Matošević',
    category: 'white',
    price: '-/235',
    year: '2016',
    location: `GRIMALDA / SOUTHERN ISTRIA, CROATIA`,
    desc: `Complex cuvee of chardonnay aged in oak and fruity & fresh sauvignon + malvasia.`,
  },
  {
    id: 8,
    title: 'GRK Bire',
    category: 'white',
    price: '-/285',
    year: '2018',
    location: `LUMBARDA - KORČULA ISLAND / SOUTHERN DALMATIA, CROATIA`,
    desc: `One of the rarest wines in the world with fruity, peppery, herbal and mineral aromas.`,
  },
  {
    id: 9,
    title: 'RIESLING AMBER Šember, organic',
    category: 'white',
    price: '-/355',
    year: '2011',
    location: `MOUNT PLEŠIVICA / CROATIAN UPLANDS, CENTRAL CROATIA`,
    desc: `Organic wine macerated on its own skins in large oak barrels, aromas of ripe fruits, dried herbs, dry leaves & flowers, candied oranges, subtle spices and vivid minerality.`,
  },
  ////////////////////////////////
  /////      RED WINES       /////
  ////////////////////////////////
  {
    id: 10,
    title: 'PLAVAC MALI Miloš, organic',
    category: 'red',
    price: '24/165',
    year: '2016',
    location: `PONIKVE / PELJEŠAC PENINSULA, SOUTHERN DALMATIA, CROATIA`,
    desc: `Dry & medium body, loaded with black fruits, sweet spices, aromatic herbs & hint of oak.`,
  },
  {
    id: 11,
    title: 'CABERNET SAUVIGNON Ritoša',
    category: 'red',
    price: '22/150',
    year: '2018',
    location: `POREČ / WESTERN ISTRIA, CROATIA`,
    desc: `Typical young CS aged in wood, wild red fruit, cassia and subtle hint of herbs and spices.`,
  },
  {
    id: 12,
    title: 'FRANKOVKA Kosovec, organic',
    category: 'red',
    price: '24/165',
    year: '2017',
    location: `POPOVAČA / MOSLAVINA, CENTRAL CROATIA`,
    desc: `Lively freshness combined with minerality, tobacco and dark fruit. Food-friendly wine.`,
  },
  {
    id: 13,
    title: 'R6 CUVÉE Bibich',
    category: 'red',
    price: '30/205',
    year: '2018',
    location: `SKRADIN / NORTHERN DALMATIA, CROATIA`,
    desc: `Medium-bodied and elegant wine, made of three indigenous grape varieties: babid, plavina and lasina, rich in dark and red fruit, herbaceous and subtle touch of oak.`,
  },
  {
    id: 14,
    title: 'OTTOCENTO CRNI Clai, organic',
    category: 'red',
    price: '-/325',
    year: '2015',
    location: `BUJE – WESTERN ISTRIA, CROATIA`,
    desc: `Full-bodied organic cuveé full of ripe red and dark fruit, figs, wood floor & leaves.`,
  },
  {
    id: 15,
    title: 'GRAN TERAN Coronica',
    category: 'red',
    price: '-/335',
    year: '2015',
    location: `UMAG / WESTERN ISTRIA, CROATIA`,
    desc: `Rich, spicy and rustic, a great wine full of dark fruits, jammy, meaty, leathery notes.`,
  },
  {
    id: 16,
    title: 'STAGNUM Miloš, organic',
    category: 'red',
    price: '770/880/990',
    year: '2009/2005/2003',
    location: `PONIKVE / PELJEŠAC / SOUTHERN DALMATIA, CROATIA`,
    desc: `Full bodied, deep and extremely complex, wine for meditation from cult croatian winemaker, aromas of dark & black fruits, carobs, figs and dates, aromatic herbs and christmas spice-box, 2003 and 2005 represent cult vintages.`,
  },
  ////////////////////////////////
  /////   SPARKLING WINES    /////
  ////////////////////////////////
  {
    id: 17,
    title: 'PROSECCO DOC Ca’ DiI Alte',
    category: 'sparkling',
    price: '24/165',
    location: `VENETO, ITALY`,
  },
  {
    id: 18,
    title: 'CHAMPAGNE ROSE BRUT Drappier',
    category: 'sparkling',
    price: '-/790',
    location: `URVILLE / CHAMPAGNE, FRANCE`,
  },
  {
    id: 19,
    title: 'VINTAGE CHAMPAGNE',
    category: 'sparkling',
    price: '-/990',
    year: '2006',
    location: `URVILLE / CHAMPAGNE, FRANCE`,
    desc: `Full bodied and full developed vintage champagne, with great complexity and rich aromas of dry leaves, ripe fruits, butter cakes, lees, nuts and mineral notes.`,
  },
  ////////////////////////////////
  ///// ROSE & SWEET  WINES  /////
  ////////////////////////////////
  {
    id: 20,
    title: 'ROSELLA ROSE Poletti',
    category: 'rose',
    price: '24/165',
    year: '2020',
    location: `VIŽINADA / WESTERN ISTRIA, CROATIA`,
    desc: `Dry, complex and fruity with notes of grenadine, rosebud, pink grapefruit & red berries.`,
  },
  {
    id: 21,
    title: 'MUŠKAT ŽUTI Štampar',
    category: 'rose',
    price: '24/165',
    year: '2019',
    location: `ŠTRIGOVA / MEĐIMURJE, CROATIAN UPLANDS`,
    desc: `Sweet type of wine. Very elegant, perfumed, notes of green grapes, fruits and flowers.`,
  },
];
